
exporter_port: 9158 # Port on which prometheu can call this exporter to get metrics
log_level: info
json_data_url: http://172.17.0.5:80/index.json # Url to get json data used for fetching metric values
metric_name_prefix: kong_cluster # All metric names will be prefixed with this value
metrics:
- name: borrowed connection # Final metric name will be kong_cluster_total_nodes
  description: MDS reported borrowed connections
  path: $.["oracle.cloudstorage.galaxy.mds.health.MdsRdbHealthCheck"]["ossstore.1.$CONFIG_SHARDS$.$DEFAULT_SHARD$"]["borrowedConnections"]
#- name: alive_nodes # Final metric name will be kong_cluster_alive_nodes
#  description: Number of live nodes in kong cluster
#  path: count($.data[@.status is "alive"])
